/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpglproj;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author pc
 */
public class AgentVente extends javax.swing.JFrame {
  public String queryG="SELECT * FROM products;";
  public String queryGS="SELECT * FROM GROS;";
  public String queryGC="SELECT * FROM commande WHERE numcom not in(SELECT numcommande from journal_commande);";
  public String queryJC="SELECT * FROM journal_commande;";
    /**
     * Creates new form 
     */
    public AgentVente() throws SQLException, ClassNotFoundException {
        initComponents();
         Tableproduct(queryG);
         Tablestock(queryGS);
         Tablecommande(queryGC);
         Tablejournal(queryJC);
       JTableHeader head = jTable1.getTableHeader();
       TableColumnModel col = jTable1.getColumnModel();
        JScrollPane scrollPane = new JScrollPane();
        jTable1.getTableHeader().setFont(new Font("sansserif",Font.BOLD,14));
         jTable1.getTableHeader().setBackground(Color.WHITE); //Does its job
        jTable1.getTableHeader().setBackground(scrollPane.getBackground());
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setForeground(new Color(0,0,0));
         jTable1.setRowHeight(35);
        stocktab.getTableHeader().setFont(new Font("sansserif",Font.BOLD,14));
         stocktab.getTableHeader().setBackground(Color.WHITE); //Does its job
        stocktab.getTableHeader().setBackground(scrollPane.getBackground());
        stocktab.getTableHeader().setOpaque(true);
                       stocktab.getTableHeader().setForeground(new Color(0,0,0));
                       stocktab.setRowHeight(35);
        
        
        jTable2.getTableHeader().setFont(new Font("sansserif",Font.BOLD,14));
         jTable2.getTableHeader().setBackground(Color.WHITE); //Does its job
        jTable2.getTableHeader().setBackground(scrollPane.getBackground());
        jTable2.getTableHeader().setOpaque(true); 
            jTable2.setRowHeight(35);        
        jTable2.getTableHeader().setForeground(new Color(0,0,0));
        
        
        journaltable.getTableHeader().setFont(new Font("sansserif",Font.BOLD,14));
         journaltable.getTableHeader().setBackground(Color.WHITE); //Does its job
        journaltable.getTableHeader().setBackground(scrollPane.getBackground());
        journaltable.getTableHeader().setOpaque(true); 
            journaltable.setRowHeight(55);        
        journaltable.getTableHeader().setForeground(new Color(0,0,0));
                  
                      
                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        productbutton = new javax.swing.JLabel();
        clientbutton = new javax.swing.JLabel();
        sells = new javax.swing.JLabel();
        clientbutton2 = new javax.swing.JLabel();
        sells1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        register = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        STOCK = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stocktab = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        deletestock = new javax.swing.JButton();
        modifystock = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        searchInput1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SELLS = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        reject = new javax.swing.JButton();
        ConfirmC = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        consult = new javax.swing.JButton();
        seachcomm = new javax.swing.JTextField();
        commandesearch = new javax.swing.JButton();
        journal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        journaltable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        inputjournal = new javax.swing.JTextField();
        searchjournal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        products = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(86, 11, 173));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\milk.png")); // NOI18N
        jLabel5.setText("MilkyWay");

        productbutton.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        productbutton.setForeground(new java.awt.Color(255, 255, 255));
        productbutton.setText("Manage products");
        productbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productbuttonMouseEntered(evt);
            }
        });

        clientbutton.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        clientbutton.setForeground(new java.awt.Color(255, 255, 255));
        clientbutton.setText("Manage Stock");
        clientbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientbuttonMouseClicked(evt);
            }
        });

        sells.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        sells.setForeground(new java.awt.Color(255, 255, 255));
        sells.setText("panding Sells");
        sells.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellsMouseClicked(evt);
            }
        });

        clientbutton2.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        clientbutton2.setForeground(new java.awt.Color(255, 255, 255));
        clientbutton2.setText("Replace CommerceA");
        clientbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientbutton2MouseClicked(evt);
            }
        });

        sells1.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        sells1.setForeground(new java.awt.Color(255, 255, 255));
        sells1.setText("Delivered Sells");
        sells1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sells1MouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        register.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Add Clients");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sells, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sells1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(productbutton))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(clientbutton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(register)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productbutton)
                .addGap(32, 32, 32)
                .addComponent(clientbutton)
                .addGap(30, 30, 30)
                .addComponent(sells)
                .addGap(29, 29, 29)
                .addComponent(sells1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(clientbutton2)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        STOCK.setBackground(new java.awt.Color(114, 9, 183));

        stocktab.setBackground(new java.awt.Color(255, 255, 251));
        stocktab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(stocktab);

        jButton7.setBackground(new java.awt.Color(45, 0, 225));
        jButton7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\plus (1).png")); // NOI18N
        jButton7.setText("    New stock");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        deletestock.setBackground(new java.awt.Color(154, 3, 30));
        deletestock.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        deletestock.setForeground(new java.awt.Color(255, 255, 255));
        deletestock.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\minus.png")); // NOI18N
        deletestock.setText("    Delete stock");
        deletestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestockActionPerformed(evt);
            }
        });

        modifystock.setBackground(new java.awt.Color(0, 114, 0));
        modifystock.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        modifystock.setForeground(new java.awt.Color(255, 255, 255));
        modifystock.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\document.png")); // NOI18N
        modifystock.setText("   Modify stock");
        modifystock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifystockActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\refresh.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        searchInput1.setBackground(new java.awt.Color(255, 255, 255));
        searchInput1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        searchInput1.setText("Search by designation");
        searchInput1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInput1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchInput1FocusLost(evt);
            }
        });
        searchInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInput1ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(86, 11, 173));
        jButton10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\search (2).png")); // NOI18N
        jButton10.setText("     Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(36, 0, 70));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("THERE'S ALWAYS A PLACE ");

        jLabel9.setBackground(new java.awt.Color(114, 9, 183));
        jLabel9.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(224, 170, 255));
        jLabel9.setText("TO GROW...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout STOCKLayout = new javax.swing.GroupLayout(STOCK);
        STOCK.setLayout(STOCKLayout);
        STOCKLayout.setHorizontalGroup(
            STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(STOCKLayout.createSequentialGroup()
                .addGroup(STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(STOCKLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(modifystock)
                        .addGap(18, 18, 18)
                        .addComponent(deletestock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(STOCKLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        STOCKLayout.setVerticalGroup(
            STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STOCKLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addGroup(STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STOCKLayout.createSequentialGroup()
                        .addGroup(STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(STOCKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modifystock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deletestock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(STOCKLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STOCKLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane1.addTab("tab1", STOCK);

        jPanel3.setBackground(new java.awt.Color(114, 9, 183));

        jPanel5.setBackground(new java.awt.Color(36, 0, 70));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRUST YOUR");

        jLabel10.setBackground(new java.awt.Color(114, 9, 183));
        jLabel10.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(224, 170, 255));
        jLabel10.setText("CLIENTS...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        reject.setBackground(new java.awt.Color(154, 3, 30));
        reject.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        reject.setForeground(new java.awt.Color(255, 255, 255));
        reject.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\minus.png")); // NOI18N
        reject.setText("    Reject");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });

        ConfirmC.setBackground(new java.awt.Color(0, 114, 0));
        ConfirmC.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        ConfirmC.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmC.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\document.png")); // NOI18N
        ConfirmC.setText("   Confirm");
        ConfirmC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmCActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\refresh.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        consult.setBackground(new java.awt.Color(60, 9, 108));
        consult.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        consult.setForeground(new java.awt.Color(255, 255, 255));
        consult.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\plus (1).png")); // NOI18N
        consult.setText("     Consult");
        consult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultActionPerformed(evt);
            }
        });

        seachcomm.setBackground(new java.awt.Color(255, 255, 255));
        seachcomm.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        seachcomm.setText("Search by commande's number");
        seachcomm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seachcommFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                seachcommFocusLost(evt);
            }
        });
        seachcomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachcommActionPerformed(evt);
            }
        });

        commandesearch.setBackground(new java.awt.Color(86, 11, 173));
        commandesearch.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        commandesearch.setForeground(new java.awt.Color(255, 255, 255));
        commandesearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\search (2).png")); // NOI18N
        commandesearch.setText("     Search");
        commandesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandesearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmC)
                        .addGap(32, 32, 32)
                        .addComponent(reject, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seachcomm, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(commandesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ConfirmC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reject, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(seachcomm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commandesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 192, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout SELLSLayout = new javax.swing.GroupLayout(SELLS);
        SELLS.setLayout(SELLSLayout);
        SELLSLayout.setHorizontalGroup(
            SELLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SELLSLayout.setVerticalGroup(
            SELLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", SELLS);

        jPanel4.setBackground(new java.awt.Color(114, 9, 183));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(36, 0, 70));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TRUST YOUR");

        jLabel13.setBackground(new java.awt.Color(114, 9, 183));
        jLabel13.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(224, 170, 255));
        jLabel13.setText("CLIENTS...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        journaltable.setBackground(new java.awt.Color(255, 255, 255));
        journaltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(journaltable);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 239, 520, 330));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\refresh.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 47));

        print.setBackground(new java.awt.Color(60, 9, 108));
        print.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\plus (1).png")); // NOI18N
        print.setText("     Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel4.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 142, 47));

        inputjournal.setBackground(new java.awt.Color(255, 255, 255));
        inputjournal.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        inputjournal.setText("Search by commande's number");
        inputjournal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputjournalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputjournalFocusLost(evt);
            }
        });
        inputjournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputjournalActionPerformed(evt);
            }
        });
        jPanel4.add(inputjournal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 40));

        searchjournal.setBackground(new java.awt.Color(86, 11, 173));
        searchjournal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        searchjournal.setForeground(new java.awt.Color(255, 255, 255));
        searchjournal.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\search (2).png")); // NOI18N
        searchjournal.setText("     Search");
        searchjournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjournalActionPerformed(evt);
            }
        });
        jPanel4.add(searchjournal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 191, 161, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\theimage.png")); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 330, 380));

        javax.swing.GroupLayout journalLayout = new javax.swing.GroupLayout(journal);
        journal.setLayout(journalLayout);
        journalLayout.setHorizontalGroup(
            journalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        journalLayout.setVerticalGroup(
            journalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", journal);

        products.setBackground(new java.awt.Color(114, 9, 183));

        jButton3.setBackground(new java.awt.Color(154, 3, 30));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\minus.png")); // NOI18N
        jButton3.setText("    Delete product");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 114, 0));
        jButton4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\document.png")); // NOI18N
        jButton4.setText("   Modify product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\refresh.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        searchInput.setBackground(new java.awt.Color(255, 255, 255));
        searchInput.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        searchInput.setText("Search by reference | by designation");
        searchInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchInputFocusLost(evt);
            }
        });
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 155, 183));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Reference", "By designation" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(86, 11, 173));
        jButton5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\search (2).png")); // NOI18N
        jButton5.setText("     Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 251));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton6.setBackground(new java.awt.Color(45, 0, 225));
        jButton6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\plus (1).png")); // NOI18N
        jButton6.setText("    New product");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productsLayout = new javax.swing.GroupLayout(products);
        products.setLayout(productsLayout);
        productsLayout.setHorizontalGroup(
            productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(productsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(productsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );
        productsLayout.setVerticalGroup(
            productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab4", products);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, -31, 880, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int option= JOptionPane.showConfirmDialog(null, "Are you sure you want to delete Product "+model.getValueAt(jTable1.getSelectedRow(), 0).toString()+" ", "Delete Product", JOptionPane.YES_NO_OPTION);
        if(option==0){
            if(jTable1.getSelectedRowCount()==1){
                try {
                    String id =(String) model.getValueAt(jTable1.getSelectedRow(), 0);
                    model.removeRow(jTable1.getSelectedRow());
                    Connect conic = new Connect();
                    Connection cnx = conic.connect();
                    PreparedStatement st= (PreparedStatement) cnx.prepareStatement("DELETE FROM products where reference='"+id+"';");
                    st.executeUpdate();
                    System.out.println(id);
                    cnx.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                } catch (ClassNotFoundException ex) {
                    System.out.println(ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "no selected row");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String id =(String) model.getValueAt(jTable1.getSelectedRow(), 0);
            new ModifyProduct(id).setVisible(true);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // TODO add your handling code here:
            Tableproduct(queryG);
        } catch (SQLException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void searchInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFocusGained
        // TODO add your handling code here:

        searchInput.setText(null);
        searchInput.setForeground(Color.black);
    }//GEN-LAST:event_searchInputFocusGained

    private void searchInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFocusLost
        // TODO add your handling code here:
        if(searchInput.getText()==null){

            searchInput.setText("Search by Refence | by Designation");
            searchInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_searchInputFocusLost

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:

            String searchedItem= searchInput.getText();
            String searchtype =(String) jComboBox1.getSelectedItem();
            Connect conic = new Connect();
            Connection cnx = conic.connect();
           
            String query1="";
            System.out.println("connected!");
            if(searchtype.compareTo("By Reference")==0){
                System.out.println(searchtype);
                query1 = "SELECT * FROM products WHERE reference='"+searchedItem+"';";
                System.out.println(query1);
            }else{
                query1 = "SELECT * FROM products WHERE designation='"+searchedItem+"';";
            }

            Tableproduct(query1);
             java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query1);

            if(res.next()){
                System.out.println("ok");
                System.err.println(res.getFloat("weight"));

            }else{
                System.out.println("rip");
            }

            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new AddProduct().setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void productbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbuttonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
      
    }//GEN-LAST:event_productbuttonMouseClicked

    private void clientbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientbuttonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
     
    }//GEN-LAST:event_clientbuttonMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Addstock().setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void deletestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestockActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) stocktab.getModel();
         
        int option= JOptionPane.showConfirmDialog(null, "Are you sure you want to delete STOCK "+model.getValueAt(stocktab.getSelectedRow(), 0).toString()+" ", "Delete Product", JOptionPane.YES_NO_OPTION);
        if(option==0){
       if(stocktab.getSelectedRowCount()==1){
           try {
               String id =(String) model.getValueAt(stocktab.getSelectedRow(), 0);
               model.removeRow(stocktab.getSelectedRow());
               Connect conic = new Connect();
               Connection cnx = conic.connect();
               PreparedStatement st= (PreparedStatement) cnx.prepareStatement("DELETE FROM GROS where designation='"+id+"';");
               st.executeUpdate();
               System.out.println(id);
               cnx.close();
           } catch (SQLException ex) {
               Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else{
           JOptionPane.showMessageDialog(null, "no selected row");
       }
        }
    }//GEN-LAST:event_deletestockActionPerformed

    private void modifystockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifystockActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) stocktab.getModel();
            String id =(String) model.getValueAt(stocktab.getSelectedRow(), 1);
             System.out.println(id);
            new ModifyStock(id).setVisible(true);
        } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_modifystockActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
      try {
          // TODO add your handling code here:
          Tablestock(queryGS);
      } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void searchInput1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInput1FocusGained
        // TODO add your handling code here:
                searchInput1.setText(null);
        searchInput1.setForeground(Color.black);
    }//GEN-LAST:event_searchInput1FocusGained

    private void searchInput1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInput1FocusLost
        // TODO add your handling code here:
          if(searchInput1.getText()==null){

            searchInput1.setText("Search by Refence | by Designation");
            searchInput1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_searchInput1FocusLost

    private void searchInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInput1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchInput1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:

            String searchedItem= searchInput1.getText();
            
            Connect conic = new Connect();
            Connection cnx = conic.connect();
           
            String query1="";
            System.out.println("connected!");
            
            

                query1 = "SELECT * FROM gros WHERE designation='"+searchedItem+"';";
            

            Tablestock(query1);
             java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query1);

            if(res.next()){
                System.out.println("ok");
                

            }else{
                System.out.println("rip");
            }

            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void sellsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellsMouseClicked
        // TODO add your handling code here:
            jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_sellsMouseClicked

    private void clientbutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientbutton2MouseClicked
      try {
          // TODO add your handling code here:
          new AGENT_commercial().setVisible(true);
          this.dispose();
      } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_clientbutton2MouseClicked

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
         
        int option= JOptionPane.showConfirmDialog(null, "Are you sure you want to reject the commande N-"+model.getValueAt(jTable2.getSelectedRow(), 0).toString()+" ", "reject Commande", JOptionPane.YES_NO_OPTION);
        if(option==0){
       if(jTable2.getSelectedRowCount()==1){
           try {
               int id =(int) model.getValueAt(jTable2.getSelectedRow(), 0);
               model.removeRow(jTable2.getSelectedRow());
               Connect conic = new Connect();
               Connection cnx = conic.connect();
               PreparedStatement st= (PreparedStatement) cnx.prepareStatement("DELETE FROM commande where numcom="+id+";");
               st.executeUpdate();
               System.out.println(id);
               cnx.close();
           } catch (SQLException ex) {
               Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else{
           JOptionPane.showMessageDialog(null, "no selected row");
       }
        }
    }//GEN-LAST:event_rejectActionPerformed

    private void ConfirmCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmCActionPerformed
      try {
          // TODO add your handling code here:
          //ONCLICK : Jpanel "ADDED TO THE JOURNAL"
          //GET COMMANDE NUMBER
          //GET CLIENT'S EMAIL
          //FILL IN THE JOURNAL WITH :
          //                              -ITEM1'S TYPE+DESIGNATION+PRICE
          //SEARCH FOR COMMANDE WITH ITS NUMBER
          
          String EmailClient="";
          String Journal="";
          DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
          int id =(int) model.getValueAt(jTable2.getSelectedRow(), 0); //commande number
          
          Connect conic = new Connect();
          Connection cnx = conic.connect();
          PreparedStatement st= (PreparedStatement) cnx.prepareStatement("SELECT * FROM commande WHERE numcom="+id+";");
          ResultSet res= st.executeQuery();
          while(res.next()){
             EmailClient=res.getString("EmailClient"); 
          }
          System.out.println(id);
       
           
          Connect conic2 = new Connect();
          Connection cnx1 = conic.connect();
          PreparedStatement stat= (PreparedStatement) cnx1.prepareStatement("SELECT * FROM items where numcom=?");
                     stat.setInt(1, id);
             ResultSet res1 = stat.executeQuery();
         
        while(res1.next()){ 
            //GET ITEMS DATA 
               System.out.println("okkk");
            Journal+="item"+res1.getInt("numitem")+"---";
             Journal+=res1.getString("designation")+"---" ;

            Journal+=res1.getString("type")+"---";
            Journal+=res1.getFloat("price")+"\n";


        }
          System.out.println(Journal);
         cnx1.close();
          //OPEN AND INSERT DATA IN JOURNAL DB


            PreparedStatement pstmt = cnx.prepareStatement(
                "INSERT INTO journal_commande" +
                " values (?, ?, ?)");

            pstmt.setString(1, EmailClient);
            pstmt.setInt(2, id);
            pstmt.setString(3, Journal);
            
       model.removeRow(jTable2.getSelectedRow());
            
            pstmt.executeUpdate();
          cnx.close();
      } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_ConfirmCActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
 try {
          // TODO add your handling code here:
          Tablecommande(queryGC);
      } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }        // TODO add your handling code here:        // TODO add your handling code here:
        
        
        
     
                
    
                
    }//GEN-LAST:event_jLabel11MouseClicked

    private void sells1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sells1MouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_sells1MouseClicked

    private void consultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultActionPerformed
      try {
          //client's email /revendeur?
          //commande number
          //cammande's items /quantity/price
          //prix finale
          //ok button
          
          // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
          int a= (int) model.getValueAt(jTable2.getSelectedRow(), 0);
          System.out.println(a);
          
          new Consultcom(a).setVisible(true);
          
          ;     } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      
      
    }//GEN-LAST:event_consultActionPerformed

    private void seachcommFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seachcommFocusGained
        // TODO add your handling code here:
                   seachcomm.setText(null);
        seachcomm.setForeground(Color.black);
    }//GEN-LAST:event_seachcommFocusGained

    private void seachcommFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seachcommFocusLost
        // TODO add your handling code here:
     
          if(seachcomm.getText()==null){

            seachcomm.setText("Search by commande Number");
            seachcomm.setForeground(Color.gray);
        }
    }//GEN-LAST:event_seachcommFocusLost

    private void seachcommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachcommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seachcommActionPerformed

    private void commandesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandesearchActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:

            String searchedCom= seachcomm.getText();
            
            Connect conic = new Connect();
            Connection cnx = conic.connect();
           
            String query1="";
            System.out.println("connected!");
            
            

                query1 = "SELECT * FROM commande WHERE numcom='"+searchedCom+"';";
            

            Tablecommande(query1);
             java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query1);

            if(res.next()){
                System.out.println("ok");
                

            }else{
                System.out.println("rip");
            }

            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_commandesearchActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
          try {
        
          Tablejournal(queryJC);
      } catch (SQLException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Journal de commande:");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        try{
            journaltable.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void inputjournalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputjournalFocusGained
        // TODO add your handling code here:
                 inputjournal.setText(null);
        inputjournal.setForeground(Color.black);
    }//GEN-LAST:event_inputjournalFocusGained

    private void inputjournalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputjournalFocusLost
        // TODO add your handling code here:
        
          if(inputjournal.getText()==null){

            inputjournal.setText("Search by commande Number");
            inputjournal.setForeground(Color.gray);
        }
    }//GEN-LAST:event_inputjournalFocusLost

    private void inputjournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputjournalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputjournalActionPerformed

    private void searchjournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjournalActionPerformed
        // TODO add your handling code here:
        
        
          try {
            // TODO add your handling code here:

    
            
            Connect conic = new Connect();
            Connection cnx = conic.connect();
           
            String query1="";
            System.out.println("connected!");
            
            

            query1 = "SELECT * FROM journal_commande WHERE numcommande="+inputjournal.getText()+";";
            

            Tablejournal(query1);
             java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query1);

            if(res.next()){
                System.out.println("ok");
                

            }else{
                JOptionPane.showMessageDialog(null, "NO journals Found!!");
            }

            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchjournalActionPerformed

    private void productbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbuttonMouseEntered
        // TODO add your handling code here:
        productbutton.setBackground(Color.gray);
    }//GEN-LAST:event_productbuttonMouseEntered

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        new ClientRegister().setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registerMouseEntered

    /**
     * @param args the command line arguments
     */
    
    
     public void Tableproduct(String query) throws SQLException, ClassNotFoundException {
     
        
         
         String[] columns = {"reference","designation","type","weight","nutrition_val","production_date","premption_date","ingredients"};
       
    Connect conic = new Connect();
            Connection cnx = conic.connect();
            java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query);
            System.out.println("connected!");
            DefaultTableModel model = new DefaultTableModel(null,columns);
            Object[] afficher=new Object[8];
        while(res.next()){
            afficher[0]=res.getString("reference") ;
        afficher[1]=res.getString("designation");
        afficher[2]=res.getString("type");
        afficher[3]=res.getString("weight");
        afficher[4]=res.getString("nutrition_val");
        afficher[5]=res.getString("production_date");
        afficher[6]=res.getString("premption_date");
        afficher[7]=res.getString("ingredients");
        model.addRow(afficher);
        }
            
            
       
           
    
        jTable1.setModel(model);
        cnx.close();
    }
    
     
     
     public void Tablestock(String query) throws SQLException, ClassNotFoundException {
     
        // ajouter quantity dachat +priux dachat
        // set quantitty dispo=quantity dachat
        // max quantity =quantity dachat-commande clients
        // 
      
         
         String[] columns = {"Type","designation","quantity_dispo","priceB","PriceCC","PriceCR"};
       
    Connect conic = new Connect();
            Connection cnx = conic.connect();
            java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query);
            System.out.println("connected!");
            DefaultTableModel model = new DefaultTableModel(null,columns);
            Object[] afficher=new Object[7];
        while(res.next()){
            afficher[0]=res.getString("Type") ;
            afficher[1]=res.getString("designation") ;
        
            afficher[2]=res.getInt("Quantity_restante");
        
            afficher[3]=res.getFloat("prix_achat");
            afficher[4]=res.getFloat("prix_client");
        afficher[5]=res.getFloat("prix_vendeur");
        model.addRow(afficher);
        }
            
            
       
           
  
        stocktab.setModel(model);
        cnx.close();
    }
     
     
          public void Tablecommande(String query) throws SQLException, ClassNotFoundException {
     
       
      
         
         String[] columns = {"commande_number","price","Client's Email"};
       
    Connect conic = new Connect();
            Connection cnx = conic.connect();
            java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query);
            System.out.println("connected!");
            DefaultTableModel model = new DefaultTableModel(null,columns);
            Object[] afficher=new Object[3];
        while(res.next()){
            afficher[0]=res.getInt("numcom") ;
            afficher[1]=res.getFloat("price") ;
        
            afficher[2]=res.getString("EmailClient");

        model.addRow(afficher);
        }
            
            
       
           
   
        jTable2.setModel(model);
        cnx.close();
    }
    
          
      public void Tablejournal(String query) throws SQLException, ClassNotFoundException {
     

      
         
         String[] columns = {"commande_number","Client's Email","Journal"};
       
    Connect conic = new Connect();
            Connection cnx = conic.connect();
            java.sql.Statement st= (java.sql.Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query);
            System.out.println("connected!");
            DefaultTableModel model = new DefaultTableModel(null,columns);
            Object[] afficher=new Object[3];
        while(res.next()){
            afficher[0]=res.getInt("numcommande") ;
            afficher[2]=res.getString("journal") ;
        
            afficher[1]=res.getString("EmailClient");

        model.addRow(afficher);
        }
            
            
       
           
        
        journaltable.setModel(model);
        cnx.close();
    }
     
          
          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AgentVente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AgentVente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmC;
    private javax.swing.JPanel SELLS;
    private javax.swing.JPanel STOCK;
    private javax.swing.JLabel clientbutton;
    private javax.swing.JLabel clientbutton2;
    private javax.swing.JButton commandesearch;
    private javax.swing.JButton consult;
    private javax.swing.JButton deletestock;
    private javax.swing.JTextField inputjournal;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel journal;
    private javax.swing.JTable journaltable;
    private javax.swing.JButton modifystock;
    private javax.swing.JButton print;
    private javax.swing.JLabel productbutton;
    private javax.swing.JPanel products;
    private javax.swing.JLabel register;
    private javax.swing.JButton reject;
    private javax.swing.JTextField seachcomm;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField searchInput1;
    private javax.swing.JButton searchjournal;
    private javax.swing.JLabel sells;
    private javax.swing.JLabel sells1;
    private javax.swing.JTable stocktab;
    // End of variables declaration//GEN-END:variables
}
